class Solution {
        public int[] lexicographicallySmallestArray(int[] nums, int limit) {
                int n = nums.length;
                        
                                // Step 1: Pair each value with its original index, then sort by value
                                        int[][] pairs = new int[n][2];
                                                for (int i = 0; i < n; i++) {
                                                            pairs[i][0] = nums[i];
                                                                        pairs[i][1] = i;
                                                                                }
                                                                                        Arrays.sort(pairs, (a, b) -> a[0] - b[0]);
                                                                                                
                                                                                                        int[] result = new int[n];
                                                                                                                int i = 0;
                                                                                                                        
                                                                                                                                while (i < n) {
                                                                                                                                            // Step 2: Find the extent of the current group
                                                                                                                                                        // A group is a run of sorted values where each is within
                                                                                                                                                                    // 'limit' of the previous one
                                                                                                                                                                                int j = i;
                                                                                                                                                                                            while (j + 1 < n && pairs[j + 1][0] - pairs[j][0] <= limit) {
                                                                                                                                                                                                            j++;
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    // Now pairs[i..j] is one connected group (all swappable with each other)
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                            // Step 3: Collect original indices in this group, sort them
                                                                                                                                                                                                                                                                        List<Integer> indices = new ArrayList<>();
                                                                                                                                                                                                                                                                                    for (int k = i; k <= j; k++) {
                                                                                                                                                                                                                                                                                                    indices.add(pairs[k][1]);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            Collections.sort(indices);
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                    // Step 4: Assign sorted values to sorted original indices
                                                                                                                                                                                                                                                                                                                                                                for (int k = i; k <= j; k++) {
                                                                                                                                                                                                                                                                                                                                                                                result[indices.get(k - i)] = pairs[k][0];
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                    i = j + 1; // move to next group
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
